### ISSUE TITLE
Migrate Store to Actor

### ISSUE THREAD

**Issue by mergesort** [mergesort/Boutique#2]
Currently this requires only a few code changes but adds warnings that I honestly am not familiar enough with to figure out the right solution, so I would be grateful for help from anyone who understands the Actor model well.

**Comment by levi** [comment]
I just found a ton of race conditions in my app because I implicitly assumed the items access in the store was thread safe. Moving to an actor would be ideal to remove all these issues in one go.

It's a fairly straight forward process, since all the operations are already marked as async. However, we will lose main thread access to the $items publisher in its current configuration. @mergesort it's been a few years since you opened this issue, and perhaps you're more familiar with the Actor api. Curious if you had any insight in what you'd like to do now?

**Comment by mergesort** [comment]
Hey @levi, sorry for the delayed reply — I'm just digging myself out of a lot of work (though heading right into my wedding so I may be busy for the next week or so as well). 😅

If it isn't too much trouble I would absolutely love to have some more examples of the race conditions you ran into, my assumption was that Boutique generally is thread safe. It would also be helpful to know if you used the SQLiteStorageEngine or the DiskStorageEngine.

More generally I plan to take a deep dive into Boutique this summer, starting with a concurrency upgrade to hopefully quell issues like this. I have from time to time ran Boutique through Swift's strict concurrency checking and only found minor warnings, and so I generally decided to wait on changes until Swift 6. I suspect that once Swift 6 is official a lot more issues will crop up given how difficult a subject concurrency is, and I thought it best to wait given how fast the concurrency APIs and effects have been changing over the last few months.

I also consider a migration to Swift 6 to be a good time to make breaking changes, for example if $items has to change. I am hoping to migrate Boutique to Observable so that may not be a huge deal, though there are a lot of caveats behind that statement given how many different types there are in Boutique that will likely have to be converted to macros.

I would also like to say that I am super open to suggestions, I consider this a collaborative process, so if you have any ideas for how to make this work I am all ears! Sorry again for the race conditions you ran into, I hope it wasn't too painful of an issue.

**Comment by levi** [comment]
@mergesort hi sorry just getting back into this now.

The issue I saw is the `performInsert` method in the store snapshots the items via `currentItems`, mutates that set via the ordered dictionary and then sets it back on the items via the main queue. Unless I put my calls to insert into the store on a serial queue, having concurrent writes to the store will lead to issues where the last call wins, which is not always the most up to date version of the set of items.

**Comment by levi** [comment]
@mergesort I migrated to something like this in my own projects:

```
import Bodega
import OrderedCollections
import Foundation

actor Store<Item: Codable & Sendable> {
    private let storageEngine: StorageEngine
    private let cacheIdentifier: KeyPath<Item, String>

    // Replace @Published with a regular property
    private var items: [Item] = []

    // Add a method to get items, since we can't use @Published
    func getItems() -> [Item] {
        items
    }

    nonisolated init(storage: StorageEngine, cacheIdentifier: KeyPath<Item, String>) {
        self.storageEngine = storage
        self.cacheIdentifier = cacheIdentifier

        // Begin loading items in the background.
        Task { await self.loadItems() }
    }

    init(storage: StorageEngine, cacheIdentifier: KeyPath<Item, String>) async throws {
        self.storageEngine = storage
        self.cacheIdentifier = cacheIdentifier
        try await self.loadItems()
    }

    private func loadItems() async throws {
        do {
            self.items = try await self.storageEngine.readAllData()
                .map({ try JSONCoders.decoder.decode(Item.self, from: $0) })
        } catch {
            self.items = []
            throw error
        }
    }

    func insert(_ item: Item) async throws {
        try await self.performInsert(item)
    }

    func insert(_ items: [Item]) async throws {
        try await self.performInsert(items)
    }

    func remove(_ item: Item) async throws {
        try await self.performRemove(item)
    }

    func remove(_ items: [Item]) async throws {
        try await self.performRemove(items)
    }

    func removeAll() async throws {
        try await self.performRemoveAll()
    }

    // Internal functions (performInsert, performRemove, etc.) remain largely the same,
    // but remove MainActor.run calls as they're no longer necessary in an actor

    private func performInsert(_ item: Item, firstRemovingExistingItems existingItemsStrategy: ItemRemovalStrategy<Item>? = nil) async throws {
        var currentItems = self.items

        if let strategy = existingItemsStrategy {
            var removedItems = [item]
            try await self.removeItemsFromStorageEngine(&removedItems, withStrategy: strategy)
            self.removeItemsFromMemory(&currentItems, withStrategy: strategy, identifier: cacheIdentifier)
        }

        let identifier = item[keyPath: self.cacheIdentifier]
        let currentItemsKeys = currentItems.map({ $0[keyPath: self.cacheIdentifier] })
        var currentValuesDictionary = OrderedDictionary<String, Item>(uniqueKeys: currentItemsKeys, values: currentItems)
        currentValuesDictionary[identifier] = item

        try await self.persistItem(item)

        self.items = Array(currentValuesDictionary.values)
    }

    // Other methods (performInsert for multiple items, performRemove, performRemoveAll) 
    // would be updated similarly, removing MainActor.run and directly modifying self.items

    // Helper methods like persistItem, removePersistedItem, etc. remain largely unchanged
}
```

```
import SwiftUI
import Combine

@Observable
class ObservableStore<Item: Codable & Sendable> {
    private let store: Store<Item>
    private var cancellables: Set<AnyCancellable> = []
    
    var items: [Item] = []
    
    init(store: Store<Item>) {
        self.store = store
        
        // Initial load of items
        Task {
            await self.refreshItems()
        }
        
        // Set up a timer to periodically refresh items
        Timer.publish(every: 1.0, on: .main, in: .common)
            .autoconnect()
            .sink { [weak self] _ in
                Task { [weak self] in
                    await self?.refreshItems()
                }
            }
            .store(in: &cancellables)
    }
    
    func refreshItems() async {
        self.items = await store.getItems()
    }
    
    func insert(_ item: Item) async throws {
        try await store.insert(item)
        await refreshItems()
    }
    
    func insert(_ items: [Item]) async throws {
        try await store.insert(items)
        await refreshItems()
    }
    
    func remove(_ item: Item) async throws {
        try await store.remove(item)
        await refreshItems()
    }
    
    func remove(_ items: [Item]) async throws {
        try await store.remove(items)
        await refreshItems()
    }
    
    func removeAll() async throws {
        try await store.removeAll()
        await refreshItems()
    }
}
```

**Comment by levi** [comment]
I've been iterating on my internal usage of Boutique. I've landed on a design that's similar to using a main and background context in CoreData. The UI can observe the store on main, updates from UI actions will be immediate and then sync'd with the background store. When I need to perform work on the background -- ie. network request -- I can interface with the actor store and it will keep the main actor store up to date.

So far this is my favorite API for a low-key replacement for CoreData.

```
/// Represents changes to the store.
public enum StoreEvent<Item> {
    case initial
    case loaded([Item])
    case insert([Item])
    case remove([Item])
}

public struct CacheKey: Hashable {
    public let value: String
    public init(_ value: String) { self.value = value }
}

public protocol StorageEngine {
    func readAllData() async throws -> [Data]
    func write(_ dataAndKeys: [(key: CacheKey, data: Data)]) async throws
    func write(_ data: Data, key: CacheKey) async throws
    func remove(key: CacheKey) async throws
    func remove(keys: [CacheKey]) async throws
    func removeAllData() async throws
}

public enum JSONCoders {
    public static let encoder = JSONEncoder()
    public static let decoder = JSONDecoder()
}

public actor CoreActorStore<Item: StorableItem> {
    private let storageEngine: StorageEngine
    private let cacheIdentifier: KeyPath<Item, String>
    private var itemsDictionary: OrderedDictionary<String, Item> = [:]

    // A subject-like mechanism for broadcasting events:
    // Each new AsyncStream created from `events()` will pick up any new events.
    // Note: AsyncStream provides a mechanism to handle multiple subscribers easily.
    private var eventContinuations = [AsyncStream<StoreEvent<Item>>.Continuation]()

    public init(storage: StorageEngine, cacheIdentifier: KeyPath<Item, String>) async throws {
        self.storageEngine = storage
        self.cacheIdentifier = cacheIdentifier

        let storedData = try await storageEngine.readAllData()
        let loadedItems = try storedData.map { try JSONCoders.decoder.decode(Item.self, from: $0) }

        // Build dictionary from loaded items
        self.itemsDictionary = OrderedDictionary(
            uniqueKeys: loadedItems.map { $0[keyPath: cacheIdentifier] },
            values: loadedItems
        )
    }

    public func events() -> AsyncStream<StoreEvent<Item>> {
        AsyncStream { continuation in
            eventContinuations.append(continuation)
            // Emit initial loaded event:
            continuation.yield(.loaded(Array(itemsDictionary.values)))
        }
    }

    // Core insert functions
    public func insert(_ items: [Item]) async throws {
        for item in items {
            itemsDictionary[item[keyPath: cacheIdentifier]] = item
        }

        let dataAndKeys = try items.map { item in
            (CacheKey(item[keyPath: cacheIdentifier]), try JSONCoders.encoder.encode(item))
        }
        try await storageEngine.write(dataAndKeys)

        emit(.insert(items))
    }

    public func insert(_ item: Item) async throws {
        try await insert([item])
    }

    // Core remove functions
    public func remove(_ items: [Item]) async throws {
        let keys = items.map { $0[keyPath: cacheIdentifier] }
        let cacheKeys = keys.map(CacheKey.init)
        try await storageEngine.remove(keys: cacheKeys)
        for key in keys {
            itemsDictionary.removeValue(forKey: key)
        }

        emit(.remove(items))
    }

    public func remove(_ item: Item) async throws {
        try await remove([item])
    }

    public func removeAll() async throws {
        try await storageEngine.removeAllData()
        let oldItems = Array(itemsDictionary.values)
        itemsDictionary.removeAll()
        emit(.remove(oldItems))
    }

    public func allItems() async -> [Item] {
        Array(itemsDictionary.values)
    }

    private func emit(_ event: StoreEvent<Item>) {
        for continuation in eventContinuations {
            continuation.yield(event)
        }
    }
}

/// A MainActor wrapper that is Observable and suitable for SwiftUI, while using a background actor for concurrency.
/// - Immediately updates the UI on writes for responsiveness.
/// - Asynchronously synchronizes with the CoreActorStore.
/// - Merges background updates into its main-thread copy of items.
@MainActor
@Observable
public final class MainActorStore<Item: StorableItem> {
    public private(set) var items: [Item] = []

    private let coreStore: CoreActorStore<Item>
    private let cacheIdentifier: KeyPath<Item, String>
    private var eventTask: Task<Void, Never>?

    public init(storage: StorageEngine, cacheIdentifier: KeyPath<Item, String>) async throws {
        self.cacheIdentifier = cacheIdentifier
        self.coreStore = try await CoreActorStore(storage: storage, cacheIdentifier: cacheIdentifier)
        self.items = await coreStore.allItems()

        // Subscribe to core store events
        self.eventTask = Task {
            let stream = await coreStore.events()
            for await event in stream {
                applyEvent(event)
            }
        }
    }

    deinit {
        eventTask?.cancel()
    }

    // MARK: - Main-Actor Writes (Optimistic UI Updates)

    public func insert(_ item: Item) {
        // Optimistically update UI
        upsertLocal(item)

        // Forward write to actor
        Task {
            do {
                try await coreStore.insert(item)
            } catch {
                // Revert changes if failed
                revertLocalChanges(forInsertedItems: [item])
            }
        }
    }

    public func insert(_ itemsToInsert: [Item]) {
        // Optimistically update UI
        let previousItems = items
        upsertLocal(itemsToInsert)

        Task {
            do {
                try await coreStore.insert(itemsToInsert)
            } catch {
                // Revert changes if failed
                items = previousItems
            }
        }
    }

    public func remove(_ item: Item) {
        // Optimistically update UI
        let previousItems = items
        removeLocal([item])

        Task {
            do {
                try await coreStore.remove(item)
            } catch {
                // Revert
                items = previousItems
            }
        }
    }

    public func remove(_ itemsToRemove: [Item]) {
        let previousItems = items
        removeLocal(itemsToRemove)

        Task {
            do {
                try await coreStore.remove(itemsToRemove)
            } catch {
                // Revert
                items = previousItems
            }
        }
    }

    public func removeAll() {
        let previousItems = items
        items.removeAll()

        Task {
            do {
                try await coreStore.removeAll()
            } catch {
                // Revert if fails
                await MainActor.run {
                    self.items = previousItems
                }
            }
        }
    }

    // MARK: - Private Helpers

    private func applyEvent(_ event: StoreEvent<Item>) {
        switch event {
        case .initial:
            // If needed, handle an initial state event
            break
        case .loaded(let loadedItems):
            self.items = loadedItems
        case .insert(let insertedItems):
            upsertLocal(insertedItems)
        case .remove(let removedItems):
            removeLocal(removedItems)
        }
    }

    /// Insert or update items in the local array.
    private func upsertLocal(_ newItems: [Item]) {
        var dictionary = Dictionary(uniqueKeysWithValues: items.map { ($0[keyPath: cacheIdentifier], $0) })
        for item in newItems {
            dictionary[item[keyPath: cacheIdentifier]] = item
        }
        items = Array(dictionary.values)
    }

    private func upsertLocal(_ newItem: Item) {
        upsertLocal([newItem])
    }

    /// Remove items from the local array.
    private func removeLocal(_ itemsToRemove: [Item]) {
        let keysToRemove = Set(itemsToRemove.map { $0[keyPath: cacheIdentifier] })
        items.removeAll { keysToRemove.contains($0[keyPath: cacheIdentifier]) }
    }

    /// If insertion fails, try to revert the inserted items.
    /// In a more advanced scenario, you might want to fetch the authoritative state from `coreStore`.
    private func revertLocalChanges(forInsertedItems insertedItems: [Item]) {
        let keys = Set(insertedItems.map { $0[keyPath: cacheIdentifier] })
        items.removeAll { keys.contains($0[keyPath: cacheIdentifier]) }
    }
}
```

**Comment by mergesort** [comment]
Hey @levi, thanks for doing all of this work and providing great context! I see you've explored the 3.0 branch where I chose to annotate Boutique's Store with @MainActor, so I want to make sure I understand the problem and use case for creating a different type that is bound to the background.

The changes in Boutique 3.0 aren't actually much different than how Boutique 2.x worked, because the `items` property (which almost everything in the Store interacts with) was bound to `@MainActor`. To compensate for this I was doing a lot of hopping to the @MainActor by using `MainActor.run`, which meant that almost all operations inside the Store were opaquely doing work on the the @MainActor. In practice I found that Boutique is almost exclusively being used in situations where the @MainActor is the correct actor to dispatch to, especially since nothing prevents you from doing heavy work in another object or context that is bound to a background actor.

All that is context to ask, do you think there much of a need to create a separate Store that is exclusively bound to a background actor? I'm having trouble envisioning a need that would necessitate the additional complexity of having two kinds of Stores, or if the scenario you proposed is not doable with the current Store set up. (I currently do similar deterministic updates in my app Plinky.)

Thanks again for the write up and for looking to make Boutique better!

**Comment by mergesort** [comment]
I'm closing this issue out because it's no longer my intention to migrate the Store to an actor after all, but if there are any reasons I should consider doing so I would appreciate reopening the issue in the future.

**Comment by levi** [comment]
The main actor approach of 3.0 does solve the original problem of write synchronization, but the tradeoff is a heavy amount of work on the main thread. I see your design goals are around simplicity, which is a great goal imo. I just love the Store API and the Data Controller pattern. What's missing for me is the ability to write from detached tasks in a non-isolated way so the main thread doesn't drop frames while I'm doing data work. Having an actor store solves this.

I've forked the project and have been working on Store2, which is a MainActor Observable and delegates writes to an actor CoreStore. It includes a sync api that writes to the main actor's memory first and then syncs the core store's memory. It also includes async apis that write directly to the core store, with the main actor store getting notified of updates after a successful write to the storage engine. It also includes a batch operation api for both the main and actor stores, so @Observable updates can be kept to a minimum during subsequent writes.

https://github.com/levi/Boutique

It's kind of its own thing at this point, but maybe it can be some inspiration for the project in the future!

**Comment by aehlke** [comment]
+1 to moving off MainActor. I need to do heavy data work on background threads without interrupting UI

**Comment by levi** [comment]
@aehlke yes i love it. It gives me the flexibility to write to main when I need to or write to background.

So far, I haven't had issues with it in my app. Some aspects of it are more personal taste, so that would be the only thing to be aware of -- ie. it lacks combine support and I experimented a bit with having an async items stream. The batch updates work well, but I think it might be a little over engineered.

But definitely check out Store2 and would love feedback if you do.

**Comment by aehlke** [comment]
@levi thanks for sharing. I'm brand new to Boutique. Do you have a minimal example of how to adopt your Store2?

**Comment by levi** [comment]
Here's the base data controller in my app:

```
import Boutique
import Foundation

let sqliteDirectory = "sqlitecache"

@MainActor
protocol DataControllerProtocol: AnyObject {
  associatedtype Item: Identifiable & Codable & Sendable & Equatable
  var items: [Item] { get }
  func find(id: Item.ID) -> Item?
  func reset()

  static var storePath: String { get }
  static func clearSQLiteFile()
}

@MainActor
class DataController<Item: Identifiable & Codable & Sendable & Equatable>: DataControllerProtocol
where Item.ID: CustomStringConvertible {
  typealias Item = Item

  let store: Store2<Item>

  class var storePath: String {
    fatalError("storePath must be overridden by subclass")
  }

  init(storePath: String? = nil) async throws {
    store = try await Store2(
      storage: SQLiteStorageEngine.default(
        appendingPath: "\(sqliteDirectory)/\(storePath ?? Self.storePath)"),
      cacheIdentifier: \.id.description
    )
  }

  class func clearSQLiteFile() {
    let fileManager = FileManager.default
    let documentsPath = fileManager.urls(for: .documentDirectory, in: .userDomainMask)[0]
    let sqlitePath = documentsPath.appendingPathComponent(sqliteDirectory).appendingPathComponent(
      storePath)

    do {
      try fileManager.removeItem(at: sqlitePath)
    } catch {
      // Ignore errors since file might not exist
    }
  }

  var items: [Item] {
    store.items
  }

  func find(id: Item.ID) -> Item? {
    store.items.first { $0.id == id }
  }

  func reset() {
    store.removeAll()
  }
}

extension DataController {
  enum Error: Swift.Error {
    case notFound
  }
}
```

Then here's an arbitrary subclass:

```
import Boutique
import Combine
import Factory
import Foundation

@MainActor
protocol ElementControllerProtocol: DataControllerProtocol {
  var elements: [Element] { get }
  func fetchAll(clusterId: UUID) async throws -> [Element]
  func create(clusterId: UUID, imageUrl: URL) async throws -> Element
  func delete(id: UUID) throws
  func find(with id: UUID) -> Element?
  func move(elementId: UUID, toClusterId: UUID) throws -> Element
  func updateCaption(elementId: UUID, caption: String?) throws -> Element
  func generateCaption(elementId: UUID) async throws -> Element
  func refresh(elementId: UUID) async throws -> Element
}

@Observable
@MainActor
final class ElementController: DataController<Element>, ElementControllerProtocol {
  enum Error: Swift.Error {
    case notFound
    case refreshFailed(underlying: Swift.Error)
    case createFailed(underlying: Swift.Error)
    case deleteFailed(underlying: Swift.Error)
    case moveFailed(underlying: Swift.Error)
    case updateFailed(underlying: Swift.Error)
    case generateCaptionFailed(underlying: Swift.Error)
  }

  var elements: [Element] {
    store.items
  }

  @ObservationIgnored
  @Injected(\.apiService) private var api

  private var cancellables: Set<AnyCancellable> = []

  override class var storePath: String {
    "Elements"
  }

  nonisolated func fetchAll(clusterId: UUID) async throws -> [Element] {
    do {
      let response = try await api.request(.element(.list(clusterId: clusterId)))
      let remote = try response.map([RemoteElement].self, using: .fractionalSecondISO8601Decoder)
      let elements = remote.map(Element.init)

      try await store.asyncBatch {
        try await store.asyncRemoveAll()
        try await store.asyncInsert(elements)
      }

      return elements
    } catch {
      throw Error.refreshFailed(underlying: error)
    }
  }

  nonisolated func create(clusterId: UUID, imageUrl: URL) async throws -> Element {
    do {
      let remote = try await api.request(
        .element(
          .create(
            originalUrl: imageUrl.absoluteString,
            contentType: "image/jpeg",
            width: nil,
            height: nil,
            caption: nil,
            clusterId: clusterId
          ))
      ).map(RemoteElement.self, using: .fractionalSecondISO8601Decoder)
      let element = Element(remote)

      try await store.asyncInsert(element)
      return element
    } catch {
      throw Error.createFailed(underlying: error)
    }
  }

  func delete(id: UUID) throws {
    guard let element = find(with: id) else {
      throw Error.notFound
    }

    store.remove(element)

    Task.detached(priority: .userInitiated) {
      do {
        _ = try await self.api.request(.element(.delete(id: id)))
      } catch {
        try await self.store.asyncInsert(element)
        throw Error.deleteFailed(underlying: error)
      }
    }
  }

  func find(with id: UUID) -> Element? {
    elements.first(where: { $0.id == id })
  }

  func move(elementId: UUID, toClusterId: UUID) throws -> Element {
    guard let element = find(with: elementId) else {
      throw Error.notFound
    }

    // Create moved element
    let movedElement = element.with(clusterId: toClusterId)

    store.remove(element)

    // Perform API request in background
    Task.detached(priority: .userInitiated) {
      do {
        _ = try await self.api.request(.element(.move(id: elementId, clusterId: toClusterId)))
      } catch {
        // On failure, revert to original
        try await self.store.asyncInsert(element)
        throw Error.moveFailed(underlying: error)
      }
    }

    return movedElement
  }

  func updateCaption(elementId: UUID, caption: String?) throws -> Element {
    guard let element = find(with: elementId) else {
      throw Error.notFound
    }

    // Create updated element
    let updatedElement = element.with(caption: caption)
    store.insert(updatedElement)

    // Perform API request in background
    Task.detached(priority: .userInitiated) {
      do {
        let remote = try await self.api.request(
          .element(.update(id: elementId, url: nil, caption: caption))
        )
        .map(RemoteElement.self, using: .fractionalSecondISO8601Decoder)
        let serverElement = Element(remote)
        try await self.store.asyncInsert(serverElement)
      } catch {
        try await self.store.asyncInsert(element)
        throw Error.updateFailed(underlying: error)
      }
    }

    return updatedElement
  }

  nonisolated func generateCaption(elementId: UUID) async throws -> Element {
    do {
      let remote = try await api.request(.element(.generateCaption(id: elementId)))
        .map(RemoteElement.self, using: .fractionalSecondISO8601Decoder)
      let element = Element(remote)
      try await self.store.asyncInsert(element)
      return element
    } catch {
      throw Error.generateCaptionFailed(underlying: error)
    }
  }

  nonisolated func refresh(elementId: UUID) async throws -> Element {
    do {
      let remote = try await api.request(.element(.get(id: elementId)))
        .map(RemoteElement.self, using: .fractionalSecondISO8601Decoder)
      let element = Element(remote)
      try await self.store.asyncInsert(element)
      return element
    } catch {
      throw Error.refreshFailed(underlying: error)
    }
  }
}
```

asyncBatch, asyncInsert, asyncRemoveAll, etc. go directly to the actor CoreStore, so they are async. These are good when writing on already a background context.

store.batch, store.insert, store.remoteAll, store.items, etc. are on the main actor isolation, will write to Store2 first and then write to CoreStore. The same is true in reverse for the async method (CoreStore first and then will sync with Store2 on main)

itemsStream lets you listen to updates from the corestore. ie.

```
      elementsTask = Task { [weak self] in
        guard let self else { return }
        for await elements in storyController.elementsStream() {
          self.elements = elements
        }
      }
```

**Comment by aehlke** [comment]
Thank you!! I'm trying it out now

**Comment by aehlke** [comment]
Ahh I just saw you upgraded the requirement to iOS 17... I need iOS 15+ sadly. Thank you though

**Comment by aehlke** [comment]
To backport `@Observable`, this can be used: https://github.com/pointfreeco/swift-perception however I couldn't figure out how to get it working with Boutique quickly. So I'm forking your library and simply removing @Observable for now as I don't need it... Cheers

**Comment by levi** [comment]
Yes it also doesn't work super well if you do have access to @observable. I recommend the item stream.

**Comment by mergesort** [comment]
Hey @levi and @aehlke, just wanted to give you an update. I'm going to keep this issue closed because I've done a lot more research, and it doesn't make sense to change the Store to be an actor. 

To reassure you, I wanted to address these comments.

> The main actor approach of 3.0 does solve the original problem of write synchronization, but the tradeoff is a heavy amount of work on the main thread. I see your design goals are around simplicity, which is a great goal imo. I just love the Store API and the Data Controller pattern. What's missing for me is the ability to write from detached tasks in a non-isolated way so the main thread doesn't drop frames while I'm doing data work. Having an actor store solves this.

> +1 to moving off MainActor. I need to do heavy data work on background threads without interrupting UI

I had a session with @mattmassicotte[^1] yesterday to make sure I properly understood the tradeoffs of moving Boutique's Store to `@MainActor`, and came away 100% convinced that this is the right choice.

The `@MainActor` annotation dictates how synchronous work should be done within a scope (types, functions, etc), not whether asynchronous work will run on the main thread. If you have heavy synchronous work within a type that's annotated `@MainActor`, then you are liable to seeing performance issues. But if you have heavy asynchronous work, then you will not incur any performance issues unless that asynchronous work is happening on the main thread _because the callee said to perform it on the main thread_. **A `@MainActor` can and will not force asynchronous work such as network requests or heavy data processing to happen on the main thread, that will only happen if the code you're calling into runs on the main thread.**

This is where the architecture of Boutique and the underlying framework [Bodega](https://github.com/mergesort/bodega) matter. All of of the code in Bodega is async and never calls to the main thread, as is almost every single line of Boutique. Even the synchronous work in Boutique is not heavy, it is all working on data in memory, and calls out to async work that will happen on a background thread. This means that all of the heavy work Boutique does is ultimately on a background thread, even with the Store having a `@MainActor` annotation.

I feel very confident about this choice, but if you have any proof otherwise, I very much welcome it! Swift Concurrency is very complicated, and it's very easy to get lost, so it's always possible that I've missed something as well.

[^1]: Who writes amazingly valuable posts about how Swift Concurrency works on his [blog](https://www.massicotte.org/), which I think everyone should read.

**Comment by levi** [comment]
I think the main issue is that it restricts app code from having to be main actor based. Bodega and Boutique don't do heavy work on the main actor, great, but now my app code has to always dispatch to the main actor just to synchronize things with Boutique. It's just not flexible enough imo.

**Comment by mattmassicotte** [comment]
Can you elaborate on exactly how you've run into this restriction?

**Comment by levi** [comment]
Yes but in my case, both my api service and CoreStore are nonisolated, so I don't have to touch the main actor at all.

**Comment by mattmassicotte** [comment]
No worries! So in that case, a `Task.detached` and plain old `Task` would be equivalent.

But I'm still very interested to hear more about the ways in which a `MainActor`-isolated Store impacts clients of the API. If you can provide an example or description that would be very useful!

**Comment by mattmassicotte** [comment]
Ahh, I completely misunderstood! You want **synchronous** access to the underlying store from the main thread, with the ability to support background that doesn't block main. This is a very reasonable request and a pretty common need for a data store.

An actor type could never provide this, because its interface must always be asynchronous. A MainActor type could maybe pull this off, but would require a lot of care and possibly an annoying API for background uses. A plain old non-Sendable reference type, which is basically equivalent to how Core Data's `NSModelObjectContext` works could be a good option. And while I personally like this approach, I'm pretty sure it would require a lot of change to the current system...

**Comment by levi** [comment]
Did you see my fork? I have Store2 and CoreStore. CoreStore is the actor store and Store2 is the MainActor copy that wraps the CoreStore.
