### ISSUE TITLE
Updating a StorageEngine after external changes

### ISSUE THREAD

**Issue by pnewell** [mergesort/Boutique#47]
I've built an initial working example of a CloudKit StorageEngine. It seems to work great/reliably, but I'm a bit stuck when it comes to updating the Store when an external change occurs. I have a decent understanding of subscribing to those changes, but how do I notify Bodega that it needs to get updates? I dont see any way to fire a resync or force it to pull fresh copies.

**Comment by mergesort** [comment]
Closed this because it's referenced in #46 where I try to answer that question and this one.
